### ISSUE TITLE
403 Forbidden result when requesting skattemelding draft

### ISSUE THREAD

**Issue by andlier** [torhovland/skattemelding#2]
Just wondering if I can get a few hints on how to proceed from this error message in case I'm doing something wrong. I've waited 3 weeks without response from skattemelding-sbs-brukerstotte@skatteetaten.no, even though they were quite responsive the first time, when asking for scope/access.

I'm successfully getting a token after logging in with bankid, using that token I get:
HTTP status client error (403 Forbidden) for url (https://idporten.api.skatteetaten.no/api/skattemelding/v2/utkast/<year>/<orgnr>)

If I use an invalid token I get 401 instead, so I think the token is correct, but my user doesn't have the right access rights somehow. 

One thing I noticed I had to do differently, was the scope I got access to by skatteetaten was named: 
skatteetaten:formueinntekt/skattemelding/eiendom,  instead of just skatteetaten:formueinntekt/skattemelding,  so I had to add /eiendom to the URL like so: https://login.idporten.no/authorize?scope=skatteetaten:formueinntekt/skattemelding/eiendom  to get the access-token.

But this also means I can't find exact matching scope-string in Altinn, where I delegate API access, I can only find: "skatteetaten:formueinntekt/skattemelding", there, but not "skatteetaten:formueinntekt/skattemelding/eiendom"  I'm not sure if this is related to the error or not.

Sorry for the long post, just looking for ideas I could try to debug this further, or points of contact I can reach out to for help.

Thanks for creating this btw! It would be very cool to be able to deliver the tax return in this way! Is the intention to enable others to deliver the return themselves, or was this project mainly for getting your own return done swiftly by yourself?

**Comment by torhovland** [comment]
The code here was implemented so that I could handle my own report, but I am putting it out here just in case it is useful to anybody.

The scope with `eiendom` seems wrong. You should be dealing with the scope as it is documented. Looks to me like they gave you the wrong access. It is too bad they are not responding to emails, while expecting everybody to deliver their reports this way.
